### ISSUE TITLE
sections overlap on cell phone

### ISSUE THREAD

**Issue by bill10** [BlackrockDigital/startbootstrap-scrolling-nav#14]
When the sections have nontrivial content, their contents seem to overlap on my iphone 7. Is there an easy solution in bootstrap? Thank you

**Comment by lauryndbrown** [comment]
Hi! I had the same problem. It's not a responsive site. I ended up using media queries to make it responsive. If you put the following css into scrolling-nav.css it should work.
`
@media screen and (max-width: 500px) {
    body {
        height: auto;
    }
}`

The problem is that the sections are inheriting their height from body to be 100%. But on smaller screens 100% is not enough room for the contents of the section. So, if you place it on auto it will make it as large as necessary to accommodate the contents. However, if you don't have enough content on larger screen sizes, it will not fill the entire height of the page. So, a media query lets you change things if the size of the width of the screen meets a certain criteria.  

Let me know if you have any questions! If it works for you, I'll see if I can't create a pull request for that solution.

**Comment by davidtmiller** [comment]
This is fixed up in the BS4 update.
