### ISSUE TITLE
The menu item not loosing focus after scroll

### ISSUE THREAD

**Issue by martinsifra** [BlackrockDigital/startbootstrap-scrolling-nav#5]
When you click on any menu item and then scroll, the focused item is still the clicked. Maybe would be better to loose the focus from menu item after scroll.

**Comment by davidtmiller** [comment]
The focused item stays focused until something else is clicked. This is an intended feature since there needs to be a focus state for usability reasons. You can change the focus state on the menu items using CSS to differentiate between a focused item and an active item. This is a good way to go about it that I've used in other themes. Hopefully this helps!
